services:
  consul:
    image: hashicorp/consul:1.20
    hostname: "consul-master"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -config-dir=/consul/config
    volumes:
      - ./data/consul-master:/consul/data
      - ./consul.json:/consul/config/consul.json
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600"
  consul2:
    image: hashicorp/consul:1.20
    hostname: "consul2"
    command: "agent -server -join consul -disable-host-node-id -config-dir=/consul/config"
    volumes:
      - ./data/consul2:/consul/data
    networks:
      - consul
    depends_on: 
      - consul
  consul3:
    image: hashicorp/consul:1.20
    hostname: "consul3"
    command: "agent -server -join consul -disable-host-node-id -config-dir=/consul/config"
    volumes:
      - ./data/consul3:/consul/data
    networks:
      - consul
    depends_on: 
      - consul
  service-1:
    image: traefik/whoami:latest
    hostname: service-1
    command:
       - --port=9001
       - --name=iamfoo
    ports:
      - 9001:9001
    networks:
      - consul
networks:
  consul:
    driver: bridge
